# Generated by Django 3.1.4 on 2020-12-27 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('born', models.IntegerField(default=0)),
                ('dead', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('ticket_price', models.IntegerField(default=0)),
                ('tickets_booked', models.IntegerField(default=0)),
                ('paintings_num', models.IntegerField(default=0)),
                ('opened_at', models.DateTimeField(verbose_name='date opened')),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('year', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.author')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.exhibition')),
            ],
        ),
    ]
