# Generated by Django 3.1.4 on 2020-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dead',
            field=models.IntegerField(null=True),
        ),
    ]
