# Generated by Django 3.1.4 on 2020-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201227_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dead',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
