# Generated by Django 3.1.4 on 2020-12-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20201227_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='paintings_num',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='tickets_booked',
        ),
    ]
