# Generated by Django 3.1.4 on 2020-12-27 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20201227_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tickets_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 21, 36, 50, 147487), verbose_name='date booked'),
        ),
    ]
