# Generated by Django 3.1.4 on 2020-12-27 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20201227_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tickets_num',
            new_name='tickets_number',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 27, 21, 37, 56, 344243), verbose_name='date booked'),
        ),
    ]
