# Generated by Django 3.1.4 on 2020-12-29 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20201227_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 7, 19, 21, 512487, tzinfo=utc), verbose_name='date booked'),
        ),
    ]
