# Generated by Django 3.1.4 on 2020-12-29 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20201229_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date booked'),
        ),
    ]
